apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat
        image: khushi5910/project:${IMAGE_TAG}
        ports:
        - containerPort: 8080
   ---
   apiVersion: v1
kind: Service
metadata:
  name: tomcat‑svc
spec:
  type: LoadBalancer
  selector:
    app: tomcat-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
